<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Twisty Passages ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-flex.min.css'))
                        ->prependStylesheet($this->basePath('css/tether.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/site.js'))
            ->prependFile($this->basePath('js/tinymce/tinymce.min.js'))
            ->prependFile($this->basePath('js/bootstrap-flex.min.js'))
            ->prependFile($this->basePath('js/tether.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ; ?>

    </head>
    <body>

        <div class="navbar-collapse collapse inverse" id="navbar-header">
            <div class="container-fluid">
                <?php echo $this->navigation('navigation')
                    ->menu()
                    ->setMinDepth(0)
                    ->setMaxDepth(0)
                    ->setPartial('partial/navigation-menu')
                    ->setAddClassToListItem(true)
                    ->setUlClass('nav navbar-nav btn-group');
                ?>
            </div>
        </div>
        <div class="navbar navbar-static-top navbar-dark bg-inverse">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation"></button>
                <a href="#" class="navbar-brand">Twisty Passages</a>
            </div>
        </div>

        <!-- flash messages -->
        <div id="flash-messages">
            <?php echo $this->partial('partial/flashmessenger.phtml'); ?>
        </div>

        <?php echo $this->content; ?>

        <footer class="text-muted">
            <div class="container">
                <!-- bread-crumbs -->
                <?php
                echo $this->navigation('navigation')
                    ->breadcrumbs()
                    ->setMinDepth(0)
                    ->setPartial('partial/breadcrumb.phtml');
                ?>
            </div>
        </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
