<section class="jumbotron text-xs-center">
    <div class="container">
        <h1 class="jumbotron-heading"><?php echo sprintf($this->translate('Log-in')); ?></h1>
        <p class="lead text-muted"><?php echo sprintf($this->translate('As a logged in user we can keep track of your story progress much better! You will also be able to up- and down-vote stories.')); ?></p>
    </div>
</section>
<div class="create-story text-muted">
    <div class="container">
        <?php
        $form = $this->loginForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/login'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('class', 'form-signin');
        ?>

        <?php echo $this->form()->openTag($form) ?>
        <?php foreach ($form as $element) : ?>

            <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                <?php
                if ('submit' != $element->getAttribute('type')) { ?>
                    <label class="control-label"><?php echo $element->getLabel() ?></label>
                    <?php
                    $element->setAttribute('class', 'form-control')
                        ->setAttribute('placeholder', $element->getLabel());
                } else {
                    $element->setAttribute('class', 'btn btn-success');
                }
                echo $this->formElement($element);
                if ($this->formElementErrors($element)) : ?>
                    <?php
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
                    ?>
                <?php endif; ?>
            </div>

            <?php
        endforeach;

        echo $this->form()->closeTag() ?>

        <?php if ($this->enableRegistration) : ?>
            <p class="text-xs-center"><?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a></p>
        <?php endif; ?>
    </div>
</div>