<section class="jumbotron text-xs-center">
    <div class="container">
        <h1 class="jumbotron-heading"><?php echo sprintf($this->translate('Sign-up')); ?></h1>
        <p class="lead text-muted"><?php echo sprintf($this->translate('As a signed-up user we can keep track of your story progress much better! You will also be able to up- and down-vote stories.')); ?></p>
    </div>
</section>
<div class="create-story text-muted">
    <div class="container">
        <?php
        if (!$this->enableRegistration) {
            print "Registration is disabled";
            return;
        }
        $form = $this->registerForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/register'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('class', 'form-signin');
        echo $this->form()->openTag($form);
        ?>

        <?php foreach ($form as $element) : ?>

            <div style="width: 780px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                <?php
                if ('submit' != $element->getAttribute('type')) { ?>
                    <label class="control-label"><?php echo $element->getLabel() ?></label>
                    <?php
                    $element->setAttribute('class', 'form-control')
                        ->setAttribute('placeholder', $element->getLabel());
                } else {
                    $element->setAttribute('class', 'btn btn-success');
                }
                if ($element instanceof Zend\Form\Element\Captcha) {
                    echo $this->formCaptcha($element);
                } else {
                    echo $this->formElement($element);
                }
                if ($this->formElementErrors($element)) : ?>
                    <?php
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
                    ?>
                <?php endif; ?>
            </div>

            <?php
        endforeach;
        if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>