<section class="jumbotron text-xs-center">
    <div class="container">
        <h1 class="jumbotron-heading"><?php echo sprintf($this->translate('Twisty Passages')); ?></h1>
        <p class="lead text-muted"><?php echo sprintf($this->translate('Welcome to this community-driven platform for interactive stories. Create your own stories with the easy-to-use yet powerful story editor for other members to enjoy!')); ?></p>
        <p>
            <a href="<?php echo $this->url('story'); ?>" class="btn btn-primary"><?php echo $this->translate('Browse stories'); ?></a>
            <a href="<?php echo $this->url('story', array('action' => 'create')); ?>" class="btn btn-secondary"><?php echo $this->translate('Create a story'); ?></a>
        </p>
    </div>
</section>

<?php echo $this->partial('twisty-passages/story/topten.phtml'); ?>
