<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Twisty Passages')); ?></h1>
    <p><?php echo sprintf($this->translate('Welcome to this community-driven platform for interactive stories. Create your own stories with the easy-to-use yet powerful story editor for other members to enjoy!')); ?></p>
    <p>
        <a class="btn btn-success btn-lg" href="#"><?php echo $this->translate('Browse stories') ?> &raquo;</a>
        <a class="btn btn-success btn-lg" href="#"><?php echo $this->translate('Create a new story') ?> &raquo;</a>
        <a class="btn btn-success btn-lg" href="https://github.com/gevrik/twistypassages" target="_blank"><?php echo $this->translate('GitHub') ?> &raquo;</a>
    </p>
</div>